---
permalink: "/:year/:month/:day/:title.html"
title: Ömer Karahan - Makina-e Mühendisi
email: omer.karahan.tr@gmail.com
description: 'Ömer Karahan - Makina-e Mühendisi - Mühendislik ve ilgilendiği diğer
  alanlarda  paylaşım yaptığı Jekyll ile güçlendirilmiş kişisel blog sitesi.'
keywords: 'Makine Mühendisliği , Hidrolik , Kalıp Tasarımı'
baseurl: ''
url: 'http://omerkarahan.com.tr'
twitter_username: o3karahan
github_username: o3karahan
paginate: 5
paginate_path: "/sayfa/page:num/"
markdown: kramdown
encoding: utf-8
gems:
- jekyll-feed
- jekyll-seo-tag
- jekyll-admin
- jekyll-sitemap
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
